load("@rules_cc//cc:defs.bzl", "cc_library")

# The very base part, without any dependency.
cc_library(
    name = "system",
    srcs = [
    ],
    hdrs = [
    ],
    deps = [
        "//gui",
    ],
    visibility = ["//visibility:public"],
)
