load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
)

# cc_library(
    # name = "mswin",
    # hdrs = [
        # "platform_spec.hpp",
    # ],
    # deps = [
        # "//nana:detail",
    # ]
    # visibility = ["//visibility:public"],
# )
