load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "pat",
    hdrs = [
        "clonable.hpp",
        "abstract_factory.hpp",
    ],
    deps = [
        "//nana/common:base",
    ]
)
